/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FeedbackForm: typeof import('./src/components/FeedbackForm.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    KvadratikiTehnika: typeof import('./src/components/kvadratiki-tehnika.vue')['default']
    NewsCards: typeof import('./src/components/NewsCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNav: typeof import('./src/components/Top-nav.vue')['default']
  }
}
